### ISSUE TITLE
I am confuse about this line ：                n_theta = (input_size + max(h//n_freq_downsample[i], 1) )

### ISSUE THREAD

**Issue by signalworker123** [cchallu/n-hits#13]
I am confuse about this line ：               
n_theta = (input_size + max(h//n_freq_downsample[i], 1) )

I think the n_theta is larger than the input_size , but freq_downsample doesn't means the output_size should smaller than input_size? 
I means inorder to do Interpolation-----the up-sampling?
Can you help me ? Thank you!!

**Comment by kdgutier** [comment]
I am referring this issue to [`NeuralForecast`'s mirror issue](https://github.com/Nixtla/neuralforecast/issues/321).
