### ISSUE TITLE
what is the  file 'hyperopt' ? 

### ISSUE THREAD

**Issue by philsau99** [cchallu/n-hits#7]
what is the  file 'hyperopt' ?

**Comment by kdgutier** [comment]
Hi @philsau99,

We are not maintaining this library. I suggest you to take a look to the [`NeuralForecast` library](https://github.com/Nixtla/neuralforecast).
Here is an example of [N-HiTS automated hyperparameter tunning](https://colab.research.google.com/drive/1WjBbQzaivQhOldGolzymOtLmo6QX4Ieg#scrollTo=HXKT2-fpUD0Z), that uses the hyperopt library.
