### ISSUE TITLE
Clarification regarding implementation

### ISSUE THREAD

**Issue by gorold** [cchallu/n-hits#8]
Hi! I have some queries about the following line of code - this seems make your implemented model somewhat different from what you specified in your paper:
https://github.com/cchallu/n-hits/blob/7b12bd3cef2e444d50803f8776b55e9606a4a1b6/src/models/nhits/nhits.py#L330
My understanding is that this line of code specifies that the final forecast also includes the first value of the lookback window, meaning you are predicting the "change in value" rather than the actual time series value. Is there any reason for doing this? Thank you for your time!

**Comment by cchallu** [comment]
Hi @gorold. You are right; the stacks predict the "change in value" from the last available value. The N-BEATS model proposed this idea, and we maintain it for the N-HiTS.

Thanks for noting is not in the paper, we will add it in future iterations of the paper.

**Comment by gorold** [comment]
Hi @cchallu, thanks for the reply. I was also wondering if it would be better to use the last value of the lookback window instead of the first value in the lookback window, mainly because the first value is sometimes masked?
