### ISSUE TITLE
Question on n_time_in

### ISSUE THREAD

**Issue by aminshabani** [cchallu/n-hits#9]
Hi,

Thank you for publishing your code and also thanks for your interesting paper. I am now trying to use your code but I am not sure if I need to update the hyper opt space for `n_time_in`?

The current settings in [nhits_multivariate](https://github.com/cchallu/n-hits/blob/main/nhits_multivariate.py#L16) is set to `'n_time_in': hp.choice('n_time_in', [5*args.horizon])` which results 960 inputs for a horizon length of 192, I was wondering is it the one used in your experiments or should I changed it to 96?

Thanks

**Comment by cchallu** [comment]
Hi @aminshabani, thanks for trying our model.

To replicate the paper's results, you should use the default hyperparameter grid search; we use the grid in nhits_multivariate for all benchmark datasets and horizons.

However, the optimal configuration might be different for other datasets and tasks. We have a forecasting general-purpose library with the N-HiTS model in https://github.com/Nixtla/neuralforecast.
